test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.671b7d2129051dc1bef663c38bd55389cce95dc0.name = "Upgrade from 5.6.0"
    

