test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9e7d3efad869f727bbf2e52e4c2e57c40651a812.name = "Upgrade from 6.1.0"
    

