test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4680975ce19dbf1fd4af2218d56cd12f43d0ae85.name = "Upgrade from 5.6.1"
    

