#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/public/;

  rewrite ^__PATH__/play/ssid/(?<ssid>.*)/type/(?<type>.*)/oid/(?<oid>[0-9]+)/uid/(?<uid>[0-9]+)/client/(?<client>.*)/noscrobble/(?<noscrobble>[0-1])/player/(?<player>.*)/name/(?<name>.*)$ __PATH__/play/index.php?ssid=$ssid&type=$type&oid=$oid&uid=$uid&client=$client&noscrobble=$noscrobble&player=$player&name=$name last;
  rewrite ^__PATH__/play/ssid/(?<ssid>.*)/type/(?<type>.*)/oid/(?<oid>[0-9]+)/uid/(?<uid>[0-9]+)/client/(?<client>.*)/noscrobble/(?<noscrobble>[0-1])/bitrate/(?<bitrate>[0-9]+)/player/(?<player>.*)/name/(?<name>.*)$ __PATH__/play/index.php?ssid=$ssid&type=$type&oid=$oid&uid=$uid&client=$client&noscrobble=$noscrobble&bitrate=$bitrate&player=$player&name=$name last;
  rewrite ^__PATH__/play/ssid/(?<ssid>.*)/type/(?<type>.*)/oid/(?<oid>[0-9]+)/uid/(?<uid>[0-9]+)/client/(?<client>.*)/noscrobble/(?<noscrobble>[0-1])/transcode_to/(?<transcode_to>w+)/bitrate/(?<bitrate>[0-9]+)/player/(?<player>.*)/name/(?<name>.*)$ __PATH__/play/index.php?ssid=$ssid&type=$type&oid=$oid&uid=$uid&client=$client&noscrobble=$noscrobble&transcode_to=$transcode_to&bitrate=$bitrate&player=$player&name=$name last;

  index index.php;

  # Common parameter to increase upload size limit in conjunction with dedicated php-fpm file
  client_max_body_size 50M;

  try_files $uri $uri/ index.php;
  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_no_auth;
  }
  
  location ^~ __PATH__/bin/ {
    deny all;
    return 403;
  }

  location ^~ __PATH__/config/ {
      deny all;
    return 403;
  }

  rewrite ^__PATH__/play/ssid/(?<ssid>\w+)/type/(?<type>\w+)/oid/(?<oid>[0-9]+)/uid/(?<uid>[0-9]+)/name/(?<name>.*)$ __PATH__/play/index.php?ssid=$ssid&type=$type&oid=$oid&uid=$uid&name=$5 last;
  rewrite ^__PATH__/play/ssid/(?<ssid>\w+)/type/(?<type>\w+)/oid/(?<oid>[0-9]+)/uid/(?<uid>[0-9]+)/client/(?<client>.*)/noscrobble/(?<noscrobble>[0-1])/name/(?<name>.*)$ __PATH__/play/index.php?ssid=$ssid&type=$type&oid=$oid&uid=$uid&client=$client&noscrobble=$noscrobble&name=$name last;

  location __PATH__/rest {

    #enable subsonic api
    if ( !-d $request_filename ) {
      rewrite ^__PATH__/rest/(?<action>.*)\.view$ __PATH__/rest/index.php?action=$action last;
      rewrite ^__PATH__/rest/fake/(.+)$ __PATH__/play/$1 last;
    }

    limit_except GET POST {
      deny all;
    }
  }
}
