#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# CHANGE AMPACHE CONFIGURATION
#=================================================
ynh_script_progression "Updating Ampache configuration..."

ynh_replace --match="\(web_path.*=.*\)\"$old_path\"" --replace="\1\"$new_path\"" --file="$install_dir/config/ampache.cfg.php"
ynh_replace --match="\(http_host.*=.*\)\"$old_domain\"" --replace="\1\"$new_domain\"" --file="$install_dir/config/ampache.cfg.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
