language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true

env:
  matrix:
    - LOWEST_DEPS="" TEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest" TEST_DEPS="tests/Sabre/"

services:
  - mysql


before_script:
  - mysql -e 'create database sabredav'
  - composer self-update
  - composer update --prefer-source $LOWEST_DEPS

script:
  - ./bin/phpunit --configuration tests/phpunit.xml $TEST_DEPS
  - ./bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

notifications:
  irc:
    channels:
        - "chat.freenode.net#sabredav"
    on_success: change
    on_failure: change
